kibana:
  enabled: true

  imagePullPolicy: ""
  replicas: 1
  port: 5601
  externalPort: 443
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  extraEnvs:
    - name: SERVER_BASEPATH
      value: "/kibana"

elasticsearch:
  master:
    enabled: true
    replicas: 1
    persistence:
      enabled: true
      ## Open Distro master Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessModes:
        - ReadWriteOnce
      size: 400M
      annotations: {}

    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 200m
        memory: 1024Mi
    javaOpts: "-Xmx256m -Xms256m"
    podAnnotations:
      fluentbit.io/exclude: "true"


  data:
    enabled: true
    ## Enables dedicated statefulset for data. Otherwise master nodes as data storage
    dedicatedPod:
      enabled: true
    replicas: 1
    updateStrategy: "RollingUpdate"

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      enabled: true

      ## Open Distro master Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessModes:
        - ReadWriteOnce
      size: 400M
      annotations: {}

    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 200m
        memory: 1024Mi
    javaOpts: "-Xmx256m -Xms256m"
    podAnnotations:
      fluentbit.io/exclude: "true"


  client:
    enabled: true
    ## Enables dedicated deployment for client/ingest. Otherwise master nodes as client/ingest
    dedicatedPod:
      enabled: true
    replicas: 1
    javaOpts: "-Xmx256m -Xms256m"

    resources:
      requests:
        cpu: "200m"
        memory: "512M"
      limits:
        cpu: "1000m"
        memory: "1024M"
    podAnnotations:
      fluentbit.io/exclude: "true"

# would like to set this but blocked by https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/121
#  config:
#    thread_pool.write.queue_size: 2000