apiVersion: v1
data:
  spartakus_volunteer_extensions: '{"seldon-core-version":"0.4.1"}'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: seldon-core-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: seldon-core-operator
    helm.sh/chart: seldon-core-operator-0.4.1
  name: seldon-spartakus-config
  namespace: kube-system
