image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - deploy

cluster-manager-maven-build:
  image: seldonio/core-builder:0.7
  stage: build
  script:
    - cd cluster-manager
    - make -f Makefile.ci build_jar
  artifacts:
    paths:
      - cluster-manager/target/*.jar
    expire_in: 1 week
  only:
    - ci_test
    - master
    - release-0.1

engine-maven-build:
  image: seldonio/core-builder:0.7
  stage: build
  script:
    - cd engine
    - make -f Makefile.ci build_jar
  artifacts:
    paths:
      - engine/target/*.jar
    expire_in: 1 week
  only:
    - ci_test
    - master
    - release-0.1

api-frontend-maven-build:
  image: seldonio/core-builder:0.7
  stage: build
  script:
    - cd api-frontend
    - make -f Makefile.ci build_jar
  artifacts:
    paths:
      - api-frontend/target/*.jar
    expire_in: 1 week
  only:
    - ci_test
    - master
    - release-0.1



pages:
  image: monachus/hugo
  stage: deploy
  script:
  - hugo -b "https://seldon-dev.gitlab.io/seldon-core/" -s=docs/ -d ../public
  artifacts:
    paths:
    - public
  only:
    - master

