separate_pods: true
modela:
  image:
    name: seldonio/mock_classifier_rest:1.3
  endpoint: REST
  name: classifier-1
#  resources: { "requests": { "memory": "1Mi" }}
modelb:
  image:
    name: seldonio/mock_classifier_rest:1.3
  endpoint: REST
  name: classifier-2
traffic_modela_percentage: 0.5
replicas: 1
# Add oauth key and secret if using the default API Oauth Gateway for ingress
oauth:
  key: 
  secret:
      
