apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: seldondeployments.machinelearning.seldon.io
spec:
  group: machinelearning.seldon.io
  names:
    kind: SeldonDeployment
    plural: seldondeployments
    shortNames:
    - sdep
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            predictors:
              items:
                properties:
                  graph:
                    properties:
                      children:
                        type: array
                        items:
                          properties:
                            children:
                              type: array
                              items:
                                properties:
                                  children:
                                    type: array
                                    items:
                                      properties:
                                        children:
                                          type: array
                                          items:
                                            properties:
                                              endpoint:
                                                properties:
                                                  grpcPort:
                                                    format: int32
                                                    type: integer
                                                  httpPort:
                                                      format: int32
                                                      type: integer
                                                  service_host:
                                                    type: string
                                                  service_port:
                                                    format: int32
                                                    type: integer
                                                  type:
                                                    type: string
                                                type: object
                                              storageInitializerImage:
                                                type: string
                                              envSecretRefName:
                                                type: string
                                              implementation:
                                                type: string
                                              methods:
                                                items:
                                                  type: string
                                                type: array
                                              modelUri:
                                                type: string
                                              name:
                                                type: string
                                              parameters:
                                                items:
                                                  properties:
                                                    name:
                                                      type: string
                                                    type:
                                                      type: string
                                                    value:
                                                      type: string
                                                  type: object
                                                type: array
                                              serviceAccountName:
                                                type: string
                                              type:
                                                type: string
                                              logger:
                                                description: Request/response  payload logging. v2alpha1 feature
                                                  that is added to v1 for backwards compatibility while v1
                                                  is the storage version.
                                                properties:
                                                  mode:
                                                    description: What payloads to log
                                                    type: string
                                                  url:
                                                    description: URL to send request logging CloudEvents
                                                    type: string
                                                type: object
                                            type: object
                                        endpoint:
                                          properties:
                                            grpcPort:
                                              format: int32
                                              type: integer
                                            httpPort:
                                              format: int32
                                              type: integer
                                            service_host:
                                              type: string
                                            service_port:
                                              format: int32
                                              type: integer
                                            type:
                                              type: string
                                          type: object
                                        storageInitializerImage:
                                          type: string
                                        envSecretRefName:
                                          type: string
                                        implementation:
                                          type: string
                                        methods:
                                          items:
                                            type: string
                                          type: array
                                        modelUri:
                                          type: string
                                        name:
                                          type: string
                                        parameters:
                                          items:
                                            properties:
                                              name:
                                                type: string
                                              type:
                                                type: string
                                              value:
                                                type: string
                                            type: object
                                          type: array
                                        serviceAccountName:
                                          type: string
                                        type:
                                          type: string
                                        logger:
                                          description: Request/response  payload logging. v2alpha1 feature
                                            that is added to v1 for backwards compatibility while v1
                                            is the storage version.
                                          properties:
                                            mode:
                                              description: What payloads to log
                                              type: string
                                            url:
                                              description: URL to send request logging CloudEvents
                                              type: string
                                          type: object
                                      type: object
                                  endpoint:
                                    properties:
                                      grpcPort:
                                        format: int32
                                        type: integer
                                      httpPort:
                                        format: int32
                                        type: integer
                                      service_host:
                                        type: string
                                      service_port:
                                        format: int32
                                        type: integer
                                      type:
                                        type: string
                                    type: object
                                  storageInitializerImage:
                                    type: string
                                  envSecretRefName:
                                    type: string
                                  implementation:
                                    type: string
                                  methods:
                                    items:
                                      type: string
                                    type: array
                                  modelUri:
                                    type: string
                                  name:
                                    type: string
                                  parameters:
                                    items:
                                      properties:
                                        name:
                                          type: string
                                        type:
                                          type: string
                                        value:
                                          type: string
                                      type: object
                                    type: array
                                  serviceAccountName:
                                    type: string
                                  type:
                                    type: string
                                  logger:
                                    description: Request/response  payload logging. v2alpha1 feature
                                      that is added to v1 for backwards compatibility while v1
                                      is the storage version.
                                    properties:
                                      mode:
                                        description: What payloads to log
                                        type: string
                                      url:
                                        description: URL to send request logging CloudEvents
                                        type: string
                                    type: object
                                type: object
                            endpoint:
                              properties:
                                grpcPort:
                                  format: int32
                                  type: integer
                                httpPort:
                                  format: int32
                                  type: integer
                                service_host:
                                  type: string
                                service_port:
                                  format: int32
                                  type: integer
                                type:
                                  type: string
                              type: object
                            storageInitializerImage:
                              type: string
                            envSecretRefName:
                              type: string
                            implementation:
                              type: string
                            methods:
                              items:
                                type: string
                              type: array
                            modelUri:
                              type: string
                            name:
                              type: string
                            parameters:
                              items:
                                properties:
                                  name:
                                    type: string
                                  type:
                                    type: string
                                  value:
                                    type: string
                                type: object
                              type: array
                            serviceAccountName:
                              type: string
                            type:
                              type: string
                            logger:
                              description: Request/response  payload logging. v2alpha1 feature
                                that is added to v1 for backwards compatibility while v1
                                is the storage version.
                              properties:
                                mode:
                                  description: What payloads to log
                                  type: string
                                url:
                                  description: URL to send request logging CloudEvents
                                  type: string
                              type: object
                          type: object
                      endpoint:
                        properties:
                          grpcPort:
                            format: int32
                            type: integer
                          httpPort:
                            format: int32
                            type: integer
                          service_host:
                            type: string
                          service_port:
                            format: int32
                            type: integer
                          type:
                            type: string
                        type: object
                      storageInitializerImage:
                        type: string
                      envSecretRefName:
                        type: string
                      implementation:
                        type: string
                      methods:
                        items:
                          type: string
                        type: array
                      modelUri:
                        type: string
                      name:
                        type: string
                      parameters:
                        items:
                          properties:
                            name:
                              type: string
                            type:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      serviceAccountName:
                        type: string
                      type:
                        type: string
                      logger:
                        description: Request/response  payload logging. v2alpha1 feature
                          that is added to v1 for backwards compatibility while v1
                          is the storage version.
                        properties:
                          mode:
                            description: What payloads to log
                            type: string
                          url:
                            description: URL to send request logging CloudEvents
                            type: string
                        type: object
                    type: object
