# Default values for seldon-core-loadtesting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  release: 0.2
replicaCount: 1
loadtest:
  id: 1
locust:
  script : predict_rest_locust.py
  host : http://seldon-apiserver:8080
  hatchRate: 1
  clients: 10
oauth:
  key: key
  secret: secret
data:
  size: 2
