apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pipelinegateway
spec:
  selector:
    matchLabels:
      app: pipelinegateway
  namespaceSelector:
    matchNames: []
    any: false
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
    path: /metrics


