openvino:
  image: intelaipg/openvino-model-server:0.2
  model:
    path: /opt/ml/squeezenet
    name: squeezenet1.1
    input: data
    output: prob
    env:
      LOG_LEVEL: DEBUG
    resources: {}
  port: 8001
  model_volume: hostPath
tfserving_proxy:
  image: seldonio/tfserving-proxy:0.2

engine:
  resources:
    requests:
      cpu: "0.1"
  env:
    SELDON_LOG_REQUESTS: false
    SELDON_LOG_RESPONSES: false
    SELDON_LOG_MESSAGES_EXTERNALLY: false

sdepLabels:
  app: "seldon"

predictorLabels:
  version: "v1"
  fluentd: "true"