apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../componentsNoConfig

# May need to add x-kubernetes-patch values for new things you want to patch if missing
openapi:
  path: crd-schema.json

patchesStrategicMerge:
- patch_controller.yaml
- patch_dataflow.yaml
- patch_envoy.yaml
- patch_hodometer.yaml
- patch_modelgateway.yaml
- patch_mlserver.yaml
- patch_pipelinegateway.yaml
- patch_scheduler.yaml
- patch_triton.yaml
- patch_kafkaconfig.yaml
- patch_tracingconfig.yaml
- patch_agentconfig.yaml
- patch_serviceconfig.yaml

patches:
- path: patch_scheduler_service.yaml
  target:
    version: v1
    kind: Service
    name: scheduler
#- path: patch_envoy_service.yaml
#  target:
#    version: v1
#    kind: Service
#    name: mesh
- path: patch_controller_json6902.yaml
  target:
    version: v1
    kind: Deployment
    name: seldon-controller-manager
- path: patch_envoy_json6902.yaml
  target:
    version: v1alpha1
    kind: SeldonConfig
    name: default
- path: patch_scheduler_json6902.yaml
  target:
    version: v1alpha1
    kind: SeldonConfig
    name: default
- path: patch_dataflow_json6902.yaml
  target:
    version: v1alpha1
    kind: SeldonConfig
    name: default
- path: patch_hodometer_json6902.yaml
  target:
    version: v1alpha1
    kind: SeldonConfig
    name: default
- path: patch_modelgateway_json6902.yaml
  target:
    version: v1alpha1
    kind: SeldonConfig
    name: default
- path: patch_pipelinegateway_json6902.yaml
  target:
    version: v1alpha1
    kind: SeldonConfig
    name: default
- path: patch_triton_serverconfig_json6902.yaml
  target:
    version: v1alpha1
    kind: ServerConfig
    name: triton
- path: patch_mlserver_serverconfig_json6902.yaml
  target:
    version: v1alpha1
    kind: ServerConfig
    name: mlserver
