- op: replace
  path: /spec/template/spec/securityContext
  value: HACK_REMOVE_ME{{- toYaml .Values.controller.securityContext | nindent 8 }}

- op: add
  path: /spec/template/metadata/annotations
  value: HACK_REMOVE_ME{{- toYaml .Values.controller.annotations | nindent  8 }}