apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seldon-scheduler
spec:
  template:
    spec:
      containers:
      - image: '{{ .Values.scheduler.image.registry }}/{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}'
        imagePullPolicy: '{{ .Values.scheduler.image.pullPolicy }}'
        name: scheduler
        env:
          - name: SCHEDULER_TLS_SECRET_NAME
            value: '{{ .Values.scheduler.tls.scheduler.server.secret }}'
          - name: SCHEDULER_TLS_FOLDER_PATH
            value: '{{ .Values.scheduler.tls.scheduler.server.folder }}'
