apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-pipelinegateway
spec:
  template:
    spec:
      imagePullSecrets:
      - name: '{{ .Values.imagePullSecret }}'
      containers:
      - image: '{{ .Values.pipelinegateway.image.registry }}/{{ .Values.pipelinegateway.image.repository }}:{{ .Values.pipelinegateway.image.tag }}'
        imagePullPolicy: '{{ .Values.pipelinegateway.image.pullPolicy }}'
        name: pipelinegateway
        resources:
          requests:
            cpu: '{{ .Values.pipelinegateway.resources.cpu }}'
            memory: '{{ .Values.pipelinegateway.resources.memory }}'
          limits:
            memory: '{{ .Values.pipelinegateway.resources.memory }}'
        env:
          - name: KAFKA_SECURITY_PROTOCOL
            value: '{{ .Values.security.kafka.protocol }}'
          - name: KAFKA_SASL_MECHANISM
            value: '{{ .Values.security.kafka.sasl.mechanism }}'
          - name: KAFKA_CLIENT_TLS_ENDPOINT_IDENTIFICATION_ALGORITHM
            value: '{{ .Values.security.kafka.ssl.client.endpointIdentificationAlgorithm }}'
          - name: KAFKA_CLIENT_TLS_SECRET_NAME
            value: '{{ .Values.security.kafka.ssl.client.secret }}'
          - name: KAFKA_CLIENT_TLS_KEY_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.keyPath }}'
          - name: KAFKA_CLIENT_TLS_CRT_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.crtPath }}'
          - name: KAFKA_CLIENT_TLS_CA_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.caPath }}'
          - name: KAFKA_CLIENT_SASL_USERNAME
            value: '{{ .Values.security.kafka.sasl.client.username }}'
          - name: KAFKA_CLIENT_SASL_SECRET_NAME
            value: '{{ .Values.security.kafka.sasl.client.secret }}'
          - name: KAFKA_CLIENT_SASL_PASSWORD_LOCATION
            value: '{{ .Values.security.kafka.sasl.client.passwordPath }}'
          - name: KAFKA_BROKER_TLS_SECRET_NAME
            value: '{{ .Values.security.kafka.ssl.client.brokerValidationSecret }}'
          - name: KAFKA_BROKER_TLS_CA_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.brokerCaPath }}'
          - name: ENVOY_SECURITY_PROTOCOL
            value: '{{ .Values.security.envoy.protocol }}'
          - name: ENVOY_UPSTREAM_SERVER_TLS_SECRET_NAME
            value: '{{ .Values.security.envoy.ssl.upstream.server.secret }}'
          - name: ENVOY_UPSTREAM_CLIENT_TLS_SECRET_NAME
            value: '{{ .Values.security.envoy.ssl.upstream.server.clientValidationSecret }}'
          - name: ENVOY_UPSTREAM_SERVER_TLS_KEY_LOCATION
            value: '{{ .Values.security.envoy.ssl.upstream.server.keyPath }}'
          - name: ENVOY_UPSTREAM_SERVER_TLS_CRT_LOCATION
            value: '{{ .Values.security.envoy.ssl.upstream.server.crtPath }}'
          - name: ENVOY_UPSTREAM_SERVER_TLS_CA_LOCATION
            value: '{{ .Values.security.envoy.ssl.upstream.server.caPath }}'
          - name: ENVOY_UPSTREAM_CLIENT_TLS_CA_LOCATION
            value: '{{ .Values.security.envoy.ssl.upstream.server.clientCaPath }}'
          - name: ENVOY_DOWNSTREAM_CLIENT_MTLS
            value: '{{ .Values.security.envoy.ssl.downstream.client.mtls }}'
          - name: ENVOY_DOWNSTREAM_CLIENT_TLS_SECRET_NAME
            value: '{{ .Values.security.envoy.ssl.downstream.client.secret }}'
          - name: ENVOY_DOWNSTREAM_SERVER_TLS_SECRET_NAME
            value: '{{ .Values.security.envoy.ssl.downstream.client.serverValidationSecret }}'
          - name: ENVOY_DOWNSTREAM_CLIENT_TLS_KEY_LOCATION
            value: '{{ .Values.security.envoy.ssl.downstream.client.keyPath }}'
          - name: ENVOY_DOWNSTREAM_CLIENT_TLS_CRT_LOCATION
            value: '{{ .Values.security.envoy.ssl.downstream.client.crtPath }}'
          - name: ENVOY_DOWNSTREAM_CLIENT_TLS_CA_LOCATION
            value: '{{ .Values.security.envoy.ssl.downstream.client.caPath }}'
          - name: ENVOY_DOWNSTREAM_SERVER_TLS_CA_LOCATION
            value: '{{ .Values.security.envoy.ssl.downstream.client.serverCaPath }}'
          - name: CONTROL_PLANE_SECURITY_PROTOCOL
            value: '{{ .Values.security.controlplane.protocol }}'
          - name: CONTROL_PLANE_CLIENT_TLS_SECRET_NAME
            value: '{{ .Values.security.controlplane.ssl.client.secret }}'
          - name: CONTROL_PLANE_SERVER_TLS_SECRET_NAME
            value: '{{ .Values.security.controlplane.ssl.client.serverValidationSecret }}'
          - name: CONTROL_PLANE_CLIENT_TLS_KEY_LOCATION
            value: '{{ .Values.security.controlplane.ssl.client.keyPath }}'
          - name: CONTROL_PLANE_CLIENT_TLS_CRT_LOCATION
            value: '{{ .Values.security.controlplane.ssl.client.crtPath }}'
          - name: CONTROL_PLANE_CLIENT_TLS_CA_LOCATION
            value: '{{ .Values.security.controlplane.ssl.client.caPath }}'
          - name: CONTROL_PLANE_SERVER_TLS_CA_LOCATION
            value: '{{ .Values.security.controlplane.ssl.client.serverCaPath }}'
