apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scheduler
  labels:
    control-plane: seldon-scheduler
spec:
  serviceName: "scheduler"  
  selector:
    matchLabels:
      control-plane: seldon-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: seldon-scheduler
    spec:
      serviceAccountName: scheduler
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - command:
        - /bin/scheduler
        args:
        - --pipeline-gateway-host=seldon-pipelinegateway
        - --tracing-config-path=/mnt/tracing/tracing.json
        - --db-path=/mnt/scheduler/db
        - --allow-plaintxt=$(ALLOW_PLAINTXT)
        image: scheduler:latest
        imagePullPolicy: IfNotPresent
        name: scheduler
        env:
          - name: ALLOW_PLAINTXT
            value: "true"
          - name: SCHEDULER_TLS_SECRET_NAME
            value: ""
          - name: SCHEDULER_TLS_FOLDER_PATH
            value: ""
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: xds
          containerPort: 9002
        - name: scheduler
          containerPort: 9004
        - name: scheduler-mtls
          containerPort: 9044
        - name: agent
          containerPort: 9005
        - name: dataflow
          containerPort: 9008
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: tracing-config-volume
          mountPath: /mnt/tracing
        - name: scheduler-state
          mountPath: /mnt/scheduler
      volumes:
      - name: tracing-config-volume
        configMap:
          name: seldon-tracing
      terminationGracePeriodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: scheduler-state
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
