resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Comment the following 3 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
#- auth_proxy_service.yaml
#- auth_proxy_role.yaml
#- auth_proxy_role_binding.yaml
- role_sas.yaml
- role_binding_sas.yaml
- role_cm.yaml
- role_binding_cm.yaml
- role_webhook.yaml
- role_binding_webhook.yaml
