version: 1

update_configs:
  - directory: "/python"
    package_manager: "python"
    update_schedule: "weekly"
    default_reviewers:
      - adriangonz
  - directory: "/executor"
    package_manager: "go:modules"
    update_schedule: "weekly"
    default_reviewers:
      - adriangonz
  - directory: "/operator"
    package_manager: "go:modules"
    update_schedule: "weekly"
    default_reviewers:
      - adriangonz
