---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow-deployment
spec:
  name: mlflow-deployment
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: gs://seldon-models/mlflow/model-a-test
        name: wines-classifier
      name: a-mlflow-deployment-dag
      replicas: 1
      traffic: 80
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: gs://seldon-models/mlflow/model-b-test
        name: wines-classifier
      name: b-mlflow-deployment-dag
      replicas: 1
      traffic: 20
