{{- if .Values.apife.enabled }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels: &Labels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: seldon-core-apiserver
    app: seldon-apiserver-container-app
    chart: {{ template "seldon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: seldon-core
  name: {{ .Release.Name }}-seldon-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels: *Labels
  template:
    metadata:
      annotations:
        prometheus.io/path: /prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels: *Labels
    spec:
      containers:
      - env:
        - name: SELDON_ENGINE_KAFKA_SERVER
          value: kafka:9092
        - name: SELDON_CLUSTER_MANAGER_REDIS_HOST
          value: {{ .Release.Name }}-redis
        - name: SELDON_CLUSTER_MANAGER_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.apife.image.name }}
        imagePullPolicy: {{ .Values.apife.image.pull_policy }}
        name: seldon-apiserver-container
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 5000
          protocol: TCP
      dnsPolicy: ClusterFirst
{{- if .Values.rbac.enabled }}
      serviceAccountName: {{ .Values.rbac.service_account.name }}
{{- end }}
      securityContext:
        runAsUser: 8888
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: seldon-core-apiserver
    app: seldon-apiserver-container-app
  name: {{ .Release.Name }}-seldon-apiserver
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: seldon-apiserver-container-app
  sessionAffinity: None
  type: {{ .Values.apife.service_type }}
status:
  loadBalancer: {}
{{- end }}
