---
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: seldon-cluster-manager
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: seldon-cluster-manager-server
      spec:
{{- if .Values.cluster_manager.rbac }}
        serviceAccountName: seldon
{{- end }}
        containers:
        - env:
          - name: JAVA_OPTS
            value: {{ .Values.cluster_manager.java_opts }}
          - name: SPRING_OPTS
            value: {{ .Values.cluster_manager.spring_opts }}
          - name: SELDON_CLUSTER_MANAGER_REDIS_HOST
            value: redis
          - name: ENGINE_CONTAINER_IMAGE_AND_VERSION
            value: seldonio/engine:{{ .Values.engine.image.tag }}
          - name: SELDON_CLUSTER_MANAGER_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: seldonio/cluster-manager:{{ .Values.cluster_manager.image.tag }}
          imagePullPolicy: {{ .Values.cluster_manager.image.pull_policy }}
          name: seldon-cluster-manager-container
          ports:
          - containerPort: 8080
            protocol: TCP
kind: List
metadata: {}
