disableAutoUpdate: false
seldonConfig: default

hodometer:
  disable: false
  replicas: 1

scheduler:
  disable: false
  replicas: 1
  # controlplane exposure
  serviceType: LoadBalancer

envoy:
  disable: false
  replicas: 1
  # dataplane exposure
  serviceType: LoadBalancer

dataflow:
  disable: false
  replicas: 1

modelgateway:
  disable: false
  replicas: 1

pipelinegateway:
  disable: false
  replicas: 1

config:
  scalingConfig:
  agentConfig:
    rclone:
      configSecrets:
  kafkaConfig:
    bootstrap:
    topicPrefix:
    consumer:
    producer:
    streams:
    topics:
  tracingConfig:
    disable:
    otelExporterEndpoint:
    otelExporterProtocol:
    ratio:
  serviceConfig:
    serviceGRPCPrefix:
    serviceType:

