---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seldon-ca
spec:
  isCA: true
  commonName: seldon-ca
  dnsNames:
  - "*.default"
  - "*.default.svc"
  - localhost
  secretName: cacert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: seldon-issuer
    kind: Issuer
    group: cert-manager.io
---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seldon-controlplane-server
spec:
  secretName: seldon-controlplane-server
  duration: 2160h
  renewBefore: 360h
  commonName: "default.svc"
  dnsNames:
  - "seldon-scheduler"
  - "seldon-scheduler.default"
  - "seldon-scheduler.default.svc"
  - "seldon-scheduler.svc"
  - localhost
  usages:
  - server auth
  - client auth
  issuerRef:
    name: seldon-ca-issuer
    kind: Issuer
---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seldon-controlplane-client
spec:
  secretName: seldon-controlplane-client
  duration: 2160h
  renewBefore: 360h
  commonName: "seldon-mesh.svc"
  dnsNames:
  - "seldon-scheduler"
  - "seldon-scheduler.default"  
  - "seldon-scheduler.default.svc"
  - "seldon-scheduler.svc"
  - localhost
  usages:
  - server auth
  - client auth
  issuerRef:
    name: seldon-ca-issuer
    kind: Issuer
---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seldon-upstream-server
spec:
  secretName: seldon-upstream-server
  duration: 2160h
  renewBefore: 360h
  commonName: "*.seldon-mesh.svc"
  dnsNames:
  - "default"
  - "*.default"    
  - "*.default.svc"
  - localhost
  usages:
  - server auth
  - client auth
  issuerRef:
    name: seldon-ca-issuer
    kind: Issuer
---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seldon-upstream-client
spec:
  secretName: seldon-upstream-client
  duration: 2160h
  renewBefore: 360h
  commonName: "*.default.svc"
  dnsNames:
  - "default"
  - "*.default"    
  - "*.default.svc"
  - localhost
  usages:
  - server auth
  - client auth
  issuerRef:
    name: seldon-ca-issuer
    kind: Issuer
---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seldon-downstream-server
spec:
  secretName: seldon-downstream-server
  duration: 2160h
  renewBefore: 360h
  commonName: "default.svc"
  dnsNames:
  - "default"    
  - "default.svc"
  - localhost
  usages:
  - server auth
  - client auth
  issuerRef:
    name: seldon-ca-issuer
    kind: Issuer
---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seldon-downstream-client
spec:
  secretName: seldon-downstream-client
  duration: 2160h
  renewBefore: 360h
  commonName: "*.default.svc"
  dnsNames:
  - "default"    
  - "*.default"    
  - "*.default.svc"
  - localhost
  usages:
  - server auth
  - client auth
  issuerRef:
    name: seldon-ca-issuer
    kind: Issuer
---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: seldon-issuer
spec:
  selfSigned: {}
---
# Source: seldon-core-v2-certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: seldon-ca-issuer
spec:
  ca:
    secretName: cacert
