---
# Source: seldon-core-v2-servers/templates/seldon-v2-servers.yaml
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver
  namespace: 'seldon-mesh'
spec:
  replicas: 1
  serverConfig: mlserver
---
# Source: seldon-core-v2-servers/templates/seldon-v2-servers.yaml
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: triton
  namespace: 'seldon-mesh'
spec:
  replicas: 1
  serverConfig: triton
