name: V1 Alibi Detect Tests

on:
  push:
    branches: [ master ]
  pull_request:
    # TODO revert before merge to master
    branches: [ fix/core-1-CVEs ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.2
          virtualenvs-create: false
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          make -C components/alibi-detect-server dev_install
      - name: Lint
        run: |
          make -C components/alibi-detect-server lint

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rclone
        run: |
          wget https://downloads.rclone.org/v1.71.2/rclone-v1.71.2-linux-amd64.zip
          unzip rclone-v1.71.2-linux-amd64.zip
          mv rclone-v1.71.2-linux-amd64/rclone /usr/local/bin/rclone
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.2
          virtualenvs-create: false
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          make -C components/alibi-detect-server dev_install
      - name: Test
        run: |
          make -C components/alibi-detect-server test
