name: AlibDetect Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-18.04
    container: seldonio/python-builder:0.6

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          make -C components/alibi-detect-server dev_install
      - name: Lint
        run: |
          make -C components/alibi-detect-server lint

  python-tests:
    runs-on: ubuntu-18.04
    container: seldonio/python-builder:0.6

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          apt-get update
          apt-get -y install ffmpeg libsm6 libxext6
          make -C components/alibi-detect-server dev_install
      - name: Test
        run: |
          make -C components/alibi-detect-server test
