name: Docs Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs-lint:

    runs-on: ubuntu-18.04
    container: seldonio/core-builder:0.19

    steps:
    - uses: actions/checkout@v2
    - name: docs-link-step
      run: |
        make -C doc install-dev linkcheck

  docs-build:

    container: seldonio/core-builder:0.19

    steps:
    - uses: actions/checkout@v2
    - name: docs-build-step
      run: |
        make -C doc install-dev html

