name: Executor Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  executor-lint:

    runs-on: ubuntu-18.04
    container: seldonio/core-builder:0.27

    steps:
    - uses: actions/checkout@v2
    - name: test-executor
      run: |
        make -C executor lint
