name: V1 Operator Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  operator-tests:

    runs-on: ubuntu-latest
    container: seldonio/core-builder:0.28

    steps:
    - uses: actions/checkout@v2
    - name: test-operator
      run: |
        make -C operator test
