name: Security Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  security-python:

    runs-on: ubuntu-latest
    container: snyk/snyk:python-3.8

    steps:
    - uses: actions/checkout@v2
    - name: security-python
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        pip install -e python/.
        snyk test --file=python/setup.py --fail-on=upgradable --severity-threshold=high

  security-operator:

    runs-on: ubuntu-latest
    container: snyk/snyk:golang

    steps:
    - uses: actions/checkout@v2
    - name: security-operator
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        make -C operator/ fmt
        snyk test --file=operator/go.mod --fail-on=upgradable --severity-threshold=high

  security-executor:

    runs-on: ubuntu-latest
    container: snyk/snyk:golang

    steps:
    - uses: actions/checkout@v2
    - name: security-executor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        make -C executor/ executor
        snyk test --file=executor/go.mod --fail-on=upgradable --severity-threshold=high

  security-image-executor:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-executor
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/seldon-core-executor:1.13.1
        args: --fail-on=upgradable --severity-threshold=high --file=executor/Dockerfile.executor

  security-image-operator:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-operator
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/seldon-core-operator:1.13.1
        args: --fail-on=upgradable --severity-threshold=high --file=operator/Dockerfile

  security-image-python-base:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-python-base
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/seldon-core-s2i-python37-ubi8:1.13.1
        args: --fail-on=upgradable --severity-threshold=high --file=wrappers/s2i/python/Dockerfile

  security-image-python-sklearn:

    runs-on: ubuntu-latest
    steps:
    - name: security-image-python-sklearn
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/sklearnserver:1.13.1
        args: --fail-on=upgradable --severity-threshold=high

  security-image-python-mlflow:

    runs-on: ubuntu-latest
    steps:
    - name: security-image-python-mlflow
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/mlflowserver:1.13.1
        args: --fail-on=upgradable --severity-threshold=high

  security-image-python-xgboost:

    runs-on: ubuntu-latest
    steps:
    - name: security-image-python-xgboost
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/xgboostserver:1.13.1
        args: --fail-on=upgradable --severity-threshold=high

  security-image-alibi-explain:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-alibi-explain
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/alibiexplainer:1.13.1
        args: --fail-on=upgradable --severity-threshold=high --file=components/alibi-explain-server/Dockerfile

  security-image-alibi-detect:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-alibi-detect
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/alibi-detect-server:1.13.1
        args: --fail-on=upgradable --severity-threshold=high --file=components/alibi-detect-server/Dockerfile

  security-image-request-logger:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-request-logger
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/seldon-request-logger:1.13.1
        args: --fail-on=upgradable --severity-threshold=high --file=components/seldon-request-logger/Dockerfile

  security-image-initializer-rclone:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-request-logger
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/rclone-storage-initializer:1.13.1
        args: --fail-on=upgradable --severity-threshold=high --file=components/rclone-storage-initializer/Dockerfile

