name: V1 Security docker image tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  security-image-executor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-executor
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/seldon-core-executor:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high --file=executor/Dockerfile.executor

  security-image-operator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-operator
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/seldon-core-operator:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high --file=operator/Dockerfile

  security-image-python-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-python-base
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/seldon-core-s2i-python3:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high --file=wrappers/s2i/python/Dockerfile

  security-image-python-sklearn:
    runs-on: ubuntu-latest
    steps:
    - name: security-image-python-sklearn
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/sklearnserver:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high

  security-image-python-mlflow:
    runs-on: ubuntu-latest
    steps:
    - name: security-image-python-mlflow
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/mlflowserver:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high

  security-image-python-xgboost:
    runs-on: ubuntu-latest
    steps:
    - name: security-image-python-xgboost
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/xgboostserver:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high

  security-image-alibi-explain:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-alibi-explain
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/alibiexplainer:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high --file=components/alibi-explain-server/Dockerfile

  security-image-alibi-detect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-alibi-detect
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/alibi-detect-server:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high --file=components/alibi-detect-server/Dockerfile

  security-image-initializer-rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: security-image-request-logger
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: seldonio/rclone-storage-initializer:1.18.2
        args: --fail-on=upgradable --app-vulns --severity-threshold=high --file=components/rclone-storage-initializer/Dockerfile
