---
name: V1 Operator Lint & Tests

on:
  push:
    branches: [master]
  pull_request:
    # TODO revert before merge to master
    branches: [release-1.19.0-prep]

  workflow_dispatch:

env:
  GOLANG_VERSION: 1.24.7

jobs:
  operator-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GOLANG_VERSION }}
    - name: lint-operator
      run: make -C operator lint

  operator-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GOLANG_VERSION }}
    - name: test-operator
      run: make -C operator test
