apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    certmanager.k8s.io/inject-ca-from: '{{ .Release.Namespace }}/seldon-serving-cert'
  creationTimestamp: null
  labels:
    app: seldon
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: '{{ include "seldon.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
  name: seldon-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: '{{ .Values.webhook.ca.crt }}'
    service:
      name: seldon-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-machinelearning-seldon-io-v1alpha2-seldondeployment
  failurePolicy: Fail
  name: mseldondeployment.kb.io
  rules:
  - apiGroups:
    - machinelearning.seldon.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - seldondeployments
