{{- if .Values.usageMetrics.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seldon-spartakus-volunteer
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: seldon-spartakus-volunteer
    spec:
      containers:
      - args:
        - volunteer
        - --cluster-id=$(SPARTAKUS_VOLUNTEER_CLUSTERID)
        - --database=$(SPARTAKUS_VOLUNTEER_DATABASE)
        - --extensions=/etc/config/spartakus.volunteer.extensions
        env:
        - name: SPARTAKUS_VOLUNTEER_CLUSTERID
          valueFrom:
            configMapKeyRef:
              key: spartakus.volunteer.clusterid
              name: seldon-spartakus-config
        - name: SPARTAKUS_VOLUNTEER_DATABASE
          valueFrom:
            configMapKeyRef:
              key: spartakus.volunteer.database
              name: seldon-spartakus-config
        image: gcr.io/google_containers/spartakus-amd64:v1.1.0
        name: seldon-spartakus-volunteer
        volumeMounts:
        - mountPath: /etc/config
          name: seldon-spartakus-config-volume
      serviceAccountName: seldon-spartakus-volunteer
      volumes:
      - configMap:
          name: seldon-spartakus-config
        name: seldon-spartakus-config-volume
{{- end }}
